# Generated by Django 6.0.3 on 2026-03-15 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('pix', 'Pix'), ('cartao_credito', 'Cartão de Crédito'), ('boleto', 'Boleto')], max_length=20)),
                ('status', models.CharField(choices=[('pendente', '⏳ Pendente'), ('aprovado', '✅ Aprovado'), ('recusado', '❌ Recusado'), ('cancelado', '🚫 Cancelado'), ('reembolsado', '↩️ Reembolsado')], default='pendente', max_length=15)),
                ('mp_payment_id', models.CharField(blank=True, max_length=100)),
                ('mp_status', models.CharField(blank=True, max_length=50)),
                ('mp_status_detail', models.CharField(blank=True, max_length=100)),
                ('pix_qr_code', models.TextField(blank=True)),
                ('pix_copia_cola', models.TextField(blank=True)),
                ('pix_expiracao', models.DateTimeField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('resposta_mp', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pagamento', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
    ]
