# Generated by Django 6.0.3 on 2026-03-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cj_imagem_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='produto',
            name='cj_product_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='cj_variant_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.CharField(choices=[('CJ', 'CJdropshipping'), ('BR', 'Imagem Folheados'), ('MANUAL', 'Manual')], default='CJ', max_length=20),
        ),
    ]
