# Generated by Django 6.0.3 on 2026-03-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_cj_imagem_url_produto_cj_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cj_product_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cj_variant_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo_fornecedor',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
